# Release Workflow
# 
# This workflow handles automated releases using semantic-release. It performs:
# - Builds the project and runs tests to ensure quality
# - Analyzes commit messages to determine version bump type
# - Creates GitHub releases with changelog
# - Publishes to npm registry with provenance attestations
# - Updates version tags and release notes
# 
# The workflow uses semantic-release to automatically:
# - Determine the next version number based on conventional commits
# - Generate changelog from commit messages
# - Create GitHub releases
# - Publish to npm with proper security attestations
# 
# Triggers: Push to master branch
# Requires: NPM_TOKEN secret for npm publishing

name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Verify the integrity of provenance attestations and registry signatures
        run: npm audit signatures

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
