name: Test Node.js 16.x

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-node16:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        registry-url: 'https://registry.npmjs.org'

    - name: Install production dependencies
      run: yarn install --frozen-lockfile --production

    - name: Build package
      run: |
        yarn add typescript@latest --dev
        yarn tsc

    - name: Pack and test
      run: |
        yarn pack
        tar -xf console-table-printer-*.tgz
        cd package
        yarn init -y
        yarn add ../console-table-printer-*.tgz
        cat > test.js << 'EOL'
        const { Table } = require('console-table-printer');
        const assert = require('assert');

        // Test basic table rendering
        const basicTable = new Table();
        basicTable.addRow({ id: 1, name: 'Test' });
        const basicRender = basicTable.render();
        assert(basicRender.includes('id'), 'Table should contain column header "id"');
        assert(basicRender.includes('name'), 'Table should contain column header "name"');
        assert(basicRender.includes('1'), 'Table should contain value "1"');
        assert(basicRender.includes('Test'), 'Table should contain value "Test"');

        // Test table with colors
        const colorTable = new Table();
        colorTable.addRow({ id: 1, name: 'Green Row' }, { color: 'green' });
        colorTable.addRow({ id: 2, name: 'Red Row' }, { color: 'red' });
        const colorRender = colorTable.render();
        assert(colorRender.includes('\x1b[32m'), 'Table should contain green color code');
        assert(colorRender.includes('\x1b[31m'), 'Table should contain red color code');

        console.log('✅ Node 16.x: Basic functionality tests passed!');
        EOL

        node test.js 