name: Test Node.js 18.x

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-node18:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'

    - name: Install production dependencies
      run: yarn install --frozen-lockfile --production

    - name: Build package
      run: |
        yarn add typescript@latest --dev
        yarn tsc

    - name: Pack and test
      run: |
        yarn pack
        tar -xf console-table-printer-*.tgz
        cd package
        yarn init -y
        yarn add ../console-table-printer-*.tgz
        cat > test.js << 'EOL'
        const { Table } = require('console-table-printer');
        const assert = require('assert');

        // Test basic table rendering
        const basicTable = new Table();
        basicTable.addRow({ id: 1, name: 'Test' });
        const basicRender = basicTable.render();
        assert(basicRender.includes('id'), 'Table should contain column header "id"');
        assert(basicRender.includes('name'), 'Table should contain column header "name"');

        // Test table with column options
        const optionsTable = new Table({
          columns: [
            { name: 'id', alignment: 'right' },
            { name: 'name', title: 'NAME' }
          ]
        });
        optionsTable.addRow({ id: 1, name: 'Test' });
        const optionsRender = optionsTable.render();
        assert(optionsRender.includes('NAME'), 'Table should contain custom column title "NAME"');

        // Test table with multiple rows and data types
        const complexTable = new Table();
        complexTable.addRows([
          { id: 1, name: 'Item 1', price: 10.99, inStock: true },
          { id: 2, name: 'Item 2', price: 20.50, inStock: false }
        ]);
        const complexRender = complexTable.render();
        assert(complexRender.includes('10.99'), 'Table should contain float value "10.99"');
        assert(complexRender.includes('true'), 'Table should contain boolean value "true"');

        console.log('✅ Node 18.x: Advanced functionality tests passed!');
        EOL

        node test.js 